## Configuration

# Log file output
# Tool will create the file if does not exists.
outfile: 'tests/outfile.txt'

# Clean any data in the output file before starting generating new logs
clear_existing_file_data: True

# List of lines to choose from
# Loggen will write these line chosen casually
template_lines: ["example line 1", "example line 2", "example line 3", "example line 4"]

# How many lines to write each time
no_bulk_lines: 10

# How many seconds to wait beetwen writes
sleep_time: 1

# Total lines to write in outfile
no_total_lines: 15

# Add number of line as a prefix for each line
prefix_no_lines: True
